- name: Turn swap off
  ansible.builtin.shell:
    cmd: sudo swapoff -a

- name: Comment out lines with "swap" in the file
  ansible.builtin.lineinfile:
    path: /etc/fstab
    regexp: '^(.* swap .*)$'
    line: '#\1'

# https://kubernetes.io/docs/setup/production-environment/container-runtimes/
# kernel modules required by setup
- name: Create k8s.conf file in the modules-load directory
  ansible.builtin.copy:
    content: |
      overlay
      br_netfilter
    dest: /etc/modules-load.d/k8s.conf
    owner: root
    group: root
    mode: '0644'

- name: Load kernel k8s modules
  ansible.builtin.command:
    cmd: modprobe overlay

- name: Load kernel k8s modules
  ansible.builtin.command:
    cmd: modprobe br_netfilter

# sysctl params required by setup, params persist across reboots
- name: Create k8s.conf file in sysctl directory
  ansible.builtin.copy:
    content: |
      net.bridge.bridge-nf-call-iptables  = 1
      net.bridge.bridge-nf-call-ip6tables = 1
      net.ipv4.ip_forward                 = 1
    dest: /etc/sysctl.d/k8s.conf
    owner: root
    group: root
    mode: '0644'

# Apply sysctl params without reboot
- name: Load kernel k8s modules
  ansible.builtin.shell:
    cmd: sysctl --system

- name: Verify iptables
  ansible.builtin.command:
    cmd: sysctl net.bridge.bridge-nf-call-iptables net.bridge.bridge-nf-call-ip6tables net.ipv4.ip_forward
  register: sysctl_config
  ignore_errors: true

- debug:
    var: sysctl_config
  ignore_errors: true

- name: Reset containerd toml file for kubernetes use
  ansible.builtin.shell:
    cmd: containerd config default | sudo tee /etc/containerd/config.toml

- name: Set systemd as cgroupdriver
  ansible.builtin.replace:
    path: /etc/containerd/config.toml
    regexp: "            SystemdCgroup = false"
    replace: "            SystemdCgroup = true"

- name: Comment out disabled plugins
  ansible.builtin.replace:
    path: /etc/containerd/config.toml
    regexp: "disabled_plugins "
    replace: "#disabled_plugins "

- name: Docker daemon config
  ansible.builtin.copy:
    content: |
      {
         "exec-opts": ["native.cgroupdriver=systemd"],
         "log-driver": "json-file",
         "log-opts": {
         "max-size": "100m"
         },
         "storage-driver": "overlay2"
      }
    dest: /etc/docker/daemon.json

- name: Reload daemons
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart containerd
  ansible.builtin.systemd:
    name: containerd
    state: restarted

- name: Restart docker
  ansible.builtin.systemd:
    name: docker
    state: restarted