# https://kubernetes.io/docs/setup/production-environment/container-runtimes/
# kernel modules required by setup
- name: Create k8s.conf file in the modules-load directory
  become: yes
  ansible.builtin.copy:
    content: |
      overlay
      br_netfilter
    dest: /etc/modules-load.d/k8s.conf
    owner: root
    group: root
    mode: '0644'

- name: Load kernel k8s modules
  become: yes
  ansible.builtin.command:
    cmd: modprobe {{ item }}
  with_items:
    - overlay
    - br_netfilter

# sysctl params required by setup, params persist across reboots
- name: Create k8s.conf file in sysctl directory
  become: yes
  ansible.builtin.copy:
    content: |
      net.bridge.bridge-nf-call-iptables  = 1
      net.bridge.bridge-nf-call-ip6tables = 1
      net.ipv4.ip_forward                 = 1
    dest: /etc/sysctl.d/k8s.conf
    owner: root
    group: root
    mode: '0644'

# Apply sysctl params without reboot
- name: Load kernel k8s modules
  become: yes
  ansible.builtin.command: sysctl --system

- name: Load kernel k8s modules
  become: yes
  ansible.builtin.command:
    cmd: lsmod | grep {{ item }}
  with_items:
    - overlay
    - br_netfilter
  register: kernel_mods
  ignore_errors: true

- debug:
    var: kernel_mods
  ignore_errors: true

- name: Verify
  become: yes
  ansible.builtin.command: sysctl net.bridge.bridge-nf-call-iptables net.bridge.bridge-nf-call-ip6tables net.ipv4.ip_forward
  register: sysctl_config
  ignore_errors: true

- debug:
    var: sysctl_config
  ignore_errors: true