- name: Copy the join command for worker nodes
  ansible.builtin.copy:
    src: node_join_command
    dest: /tmp/node_join_command.sh
    mode: '0777'

- name: Add containerd socket
  ansible.builtin.replace:
    path: /tmp/node_join_command.sh
    regexp: "--token"
    replace: "--cri-socket='unix:///run/cri-dockerd.sock' --token"

- name: Join the worker node to cluster
  ansible.builtin.command: sh /tmp/node_join_command.sh