apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cap-cars-pv-claim
  namespace: cap-cars-app
  labels:
    app: mysql
    tier: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: cap-cars-app
  labels:
    app: mysql
    tier: database
spec:
  selector:
    matchLabels:
      app: mysql
      tier: database
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
        tier: database
    spec:
      containers:
        - image: mysql
          name: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom :
                secretKeyRef :
                  name : cap-cars-secrets
                  key :  password

            - name: MYSQL_DATABASE
              valueFrom :
                configMapKeyRef :
                  name : cap-db-config
                  key :  dbName
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: cap-cars-pv
              mountPath: /var/lib/mysql
      volumes:
        - name: cap-cars-pv
          persistentVolumeClaim:
            claimName: cap-cars-pv-claim

---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: cap-cars-app
  labels:
    app: mysql
    tier: database
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: mysql
    tier: database
  clusterIP: None