---
### Install Dependencies, Docker, & Kubernetes
- hosts: all
  become: true
  vars:
   - dependencies:
       - ca-certificates
       - curl
       - gnupg
       - apt-transport-https
   - docker:
       - docker-ce
       - docker-ce-cli
       - containerd.io
       - docker-buildx-plugin
       - docker-compose-plugin
   - kubernetes:
       - kubeadm
       - kubectl
       - kubelet
   - net:
       - net-tools
       - dnsutils
       - traceroute
       - telnet
       - tshark
  roles:
    - tools_install
    - vm_setup
    #- cri-dockerd_config
##

### Copy Kubernetes Manifest Files
- hosts: control-plane
  become: true
  roles:
    - k8s_manifests

### Master Node Configurations
- hosts: control-plane-leader
  become: true
  vars_files:
    - ansible_vars_file.yml
  roles:
    - control_plane_leader
##

### Configure other master nodes
- hosts: control-plane-followers
  become: true
  vars_files:
    - ansible_vars_file.yml
  roles:
    - control_plane_followers
##

### Worker Node Configurations
- hosts: workers
  become: true
  roles:
    - worker_nodes
##

### Create Admin User and Install and Configure App
- hosts: control-plane-leader
  become: true
  roles:
    - admin_user_creation

- hosts:
    - control-plane-followers
    - workers
  become: true
  roles:
    - admin_user_install

- hosts: control-plane-leader
  become: true
  roles:
    - install_app