- hosts: all
  become: true
  variables:
    - net:
        - net-tools
        - dnsutils
        - traceroute
        - telnet
        - tshark
        - nmap
  tasks:
    - name: Install network tools
      ansible.builtin.apt:
        name: "{{ net }}"
        state: present