##  https://github.com/Mirantis/cri-dockerd
- name: Clone Mirantis/cri-dockerd repo
  ansible.builtin.git:
    repo: https://github.com/Mirantis/cri-dockerd.git
    dest: $HOME/cri-dockerd
    single_branch: yes
    version: master

- name: Download golang build tools
  ansible.builtin.get_url:
    url: https://storage.googleapis.com/golang/getgo/installer_linux
    dest: $HOME/installer_linux
    mode: '0755'

- name: Install GO
  ansible.builtin.shell:
    cmd: "$HOME/installer_linux && source /root/.bash_profile && go version"
    executable: /bin/bash
  register: go_version_output

- name: Display GO version
  ansible.builtin.debug:
    var: go_version_output.stdout

- name: Build cri-dockerd
  shell:
    cmd: "source /root/.bash_profile && cd $HOME/cri-dockerd && mkdir -p bin && go build -o bin/cri-dockerd"
    executable: /bin/bash
  args:
    creates: $HOME/cri-dockerd/bin/cri-dockerd

- name: Create a /usr/local/bin directory if it does not exist
  ansible.builtin.file:
    path: /usr/local/bin
    state: directory
    mode: '0755'

- name: Install cri-dockerd binary in /usr/local/bin/ directory
  ansible.builtin.copy:
    src: $HOME/cri-dockerd/bin/cri-dockerd
    dest: /usr/local/bin/cri-dockerd
    remote_src: true
    owner: root
    group: root
    mode: '0755'

- name: Copy packaging/systemd/* to /etc/systemd/system directory
  ansible.builtin.copy:
    src: $HOME/cri-dockerd/packaging/systemd/{{ item }}
    dest: /etc/systemd/system/{{ item }}
    remote_src: true
  with_items:
    - cri-docker.service
    - cri-docker.socket

- name: Configure systemd for cri-dockerd
  ansible.builtin.replace:
    path: /etc/systemd/system/cri-docker.service
    regexp: "/usr/bin/cri-dockerd"
    replace: "/usr/local/bin/cri-dockerd"

- name: Just force systemd to reread configs
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Start and Enable the cri-dockerd service - cri-docker.service
  ansible.builtin.systemd:
    name: cri-docker.service
    state: started
    enabled: yes

- name: Start and Enable the cri-dockerd service - cri-docker.socket
  ansible.builtin.systemd:
    name: cri-docker.socket
    state: started
    enabled: yes

- name: restart docker
  ansible.builtin.systemd:
    name: docker
    state: restarted

- name: restart kubelet
  ansible.builtin.systemd:
    name: kubelet
    state: restarted

