- name: Set hostnames
  ansible.builtin.shell:
    cmd: hostnamectl set-hostname "{{ inventory_hostname }}"

### https://docs.docker.com/engine/install/ubuntu/
- name: Install Dependencies
  ansible.builtin.apt:
    name: "{{ dependencies }}"
    state: present

- name: Update Cache
  ansible.builtin.apt:
    update_cache: true

### Docker
- name: Install Keyring Directory
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Install Docker GPG Key
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'
    force: true

- name: Install Docker Repository
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    filename: /etc/apt/sources.list.d/docker
    state: present
    update_cache: true

- name: Install Docker Bundle
  ansible.builtin.apt:
    name: "{{ docker }}"
    state: present

- name: Enable Docker
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: true

### CNI Plugins
- name: Make CNI directory
  ansible.builtin.file:
    path: /opt/cni/bin
    state: directory

- name: Download CNI plugins archive
  become: yes
  get_url:
    url: https://github.com/containernetworking/plugins/releases/download/v1.1.1/cni-plugins-linux-amd64-v1.1.1.tgz
    dest: /tmp/cni-plugins-linux-amd64-v1.1.1.tgz

- name: Extract CNI plugins archive
  become: yes
  unarchive:
    src: /tmp/cni-plugins-linux-amd64-v1.1.1.tgz
    dest: /opt/cni/bin
    remote_src: yes
    extra_opts: "-z"

### Kubernetes
- name: Add Kubernetes GPG Key
  ansible.builtin.get_url:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    dest: /etc/apt/keyrings/kubernetes-archive-keyring.asc
    mode: '0644'
    force: true

- name: Sleep for 20 seconds
  ansible.builtin.wait_for:
    timeout: 20

- name: Verify presence of GPG Key
  ansible.builtin.stat:
    path: /etc/apt/keyrings/kubernetes-archive-keyring.asc
  register: gpg_key

- name: Add Kubernetes Repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/kubernetes-archive-keyring.asc] https://apt.kubernetes.io/ kubernetes-xenial main"
    filename: /etc/apt/sources.list.d/kubernetes.list
    state: present
  when: gpg_key.stat.exists

- name: Update Cache
  ansible.builtin.apt:
    update_cache: true

- name: Kubernetes Bundle Install
  ansible.builtin.apt:
    name: "{{ kubernetes }}"
    state: present

- name: Install network tools
  ansible.builtin.apt:
    name: "{{ net }}"
    state: present
