apiVersion: v1
kind: PersistentVolume
metadata:
  name: cap-cars-pv
  namespace: cap-car-app
spec:
  hostPath:
    path: /var/lib/mysql
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
