apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cluster-admin-rb
  namespace: cap-quotes-app
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cluster-admin
subjects:
  - kind: User
    name: devopsadmin
    apiGroup: rbac.authorization.k8s.io
    namespace: cap-quotes-app
