apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cap-quotes-pv-claim
  namespace: cap-quotes-app
  labels:
    app: mysql
    tier: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: cap-quotes-app
  labels:
    app: mysql
    tier: database
spec:
  selector:
    matchLabels:
      app: mysql
      tier: database
      role: db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
        tier: database
        role: db
    spec:
      hostname: mysql
      containers:
        - image: mysql
          name: mysql
          env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: cap-quotes-secrets
                key: rootPassword
          - name: MYSQL_ROOT_HOST
            valueFrom:
              secretKeyRef:
                name: cap-quotes-secrets
                key: host
          - name: MYSQL_DATABASE
            valueFrom:
              secretKeyRef:
                name: cap-quotes-secrets
                key: dbName
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                name: cap-quotes-secrets
                key: username
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: cap-quotes-secrets
                key: password
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: cap-quotes-pv
              mountPath: /var/lib/mysql
            - name: cap-quotes-dbcreation-script
              mountPath: /docker-entrypoint-initdb.d #https://hub.docker.com/_/mysql Refer Initializing a fresh instance
      volumes:
        - name: cap-quotes-pv
          persistentVolumeClaim:
            claimName: cap-quotes-pv-claim
        - name: cap-quotes-dbcreation-script
          configMap:
            name: cap-quotes-dbcreation-script
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: cap-quotes-app
  labels:
    app: mysql
    tier: database
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: mysql
    tier: database
  clusterIP: None