apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: cap-quotes-hpa
  namespace: cap-quotes-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cap-quotes-app
  minReplicas: 1
  maxReplicas: 20
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
        - type: Percent
          value: 100
          periodSeconds: 15
