apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: cap-cars-hpa
  namespace: cap-cars-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cap-cars-app
  minReplicas: 1
  maxReplicas: 20
  targetCPUUtilizationPercentage: 50