apiVersion: v1
kind: ConfigMap
metadata:
  name: cap-quotes-dbcreation-script
  namespace: cap-quotes-app
data:
  mysql_usermgmt.sql: |-
    CREATE DATABASE  IF NOT EXISTS `quotes_database` /*!40100 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci */ /*!80016 DEFAULT ENCRYPTION='N' */;
    USE `quotes_database`;
    -- MySQL dump 10.13  Distrib 8.0.32, for Win64 (x86_64)
    --
    -- Host: localhost    Database: quotes_database
    -- ------------------------------------------------------
    -- Server version	8.0.32
    
    /*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
    /*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
    /*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
    /*!50503 SET NAMES utf8 */;
    /*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
    /*!40103 SET TIME_ZONE='+00:00' */;
    /*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
    /*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
    /*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
    /*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
    
    --
    -- Table structure for table `quotes`
    --
    
    DROP TABLE IF EXISTS `quotes`;
    /*!40101 SET @saved_cs_client     = @@character_set_client */;
    /*!50503 SET character_set_client = utf8mb4 */;
    CREATE TABLE `quotes` (
      `quoteID` bigint NOT NULL AUTO_INCREMENT,
      `quote_string` varchar(255) DEFAULT NULL,
      PRIMARY KEY (`quoteID`)
    ) ENGINE=InnoDB AUTO_INCREMENT=8 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
    /*!40101 SET character_set_client = @saved_cs_client */;
    
    --
    -- Dumping data for table `quotes`
    --
    
    LOCK TABLES `quotes` WRITE;
    /*!40000 ALTER TABLE `quotes` DISABLE KEYS */;
    INSERT INTO `quotes` VALUES (1,'Who in my life has shown up for me in the biggest way?'),(2,'What\'s been my happiest memory the past few weeks?'),(3,'What have I learned that I need more of?'),(4,'What have I learned that I need less of?'),(5,'What has most surprised me about myself recently?'),(6,'What do I want to prioritize for myself in the coming months?'),(7,'What did I most take for granted before this time that I want to more fully appreciate moving forward?');
    /*!40000 ALTER TABLE `quotes` ENABLE KEYS */;
    UNLOCK TABLES;
    
    --
    -- Dumping routines for database 'quotes_database'
    --
    /*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;
    
    /*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
    /*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
    /*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
    /*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
    /*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
    /*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
    /*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
    
    -- Dump completed on 2023-06-14 11:53:21
