apiVersion: v1
kind: ConfigMap
metadata:
  name: cap-cars-dbcreation-script
  namespace: cap-cars-app
data:
  mysql_usermgmt.sql: |-
    DROP DATABASE IF EXISTS capcarsdb;
    CREATE DATABASE capcarsdb;